[Fix] Add Ollama Message API Support for Text
GenseeAI/cognify pull request #12
Opened 2024-12-06 20:36 UTC by reyna-abhyankar

Closes #10 

- [x] Adds a wrapper around `litellm.completion` which parses down the message from `"content": [{"type": "text", "text": "xyz"}]` to `"content": "xyz"` for ollama. As mentioned in #11 , the former _should_ still be compatible when looking at the ollama codebase, so we should investigate in more detail when making the fix for images.
- [x] Add error handling for DSPy in case structured output returns an empty value for an expected field

Also adds the following:
- [x] Add evaluator-level error handling in case a workflow throws an error. Instead of raising the error and exiting, we log the error and treat that individual result as invalid. The use case for this is the model generating output that is "wrong" from the perspective of the workflow developer (e.g., not structured correctly, incorrect tool call). The workflow will throw an error upon executing. But since it may be specific to a particular training example or non-deterministic, we shouldn't kill the optimizer. **If this is controversial, I can move it to a separate PR and we can merge this one.**

2024-12-09 01:23 UTC, yiying-zhang approved these changes

2024-12-12 20:37 UTC, jiange91 requested changes
Might need small refactoring in the error handling. Others look good to me.

2024-12-12 20:37 UTC, jiange91 commented on cognify/optimizer/evaluator.py
>          except Exception as e:
Can you resolve the workflow error in this handler? Otherwise ctl+c can be caught in both try blocks.

2024-12-12 20:45 UTC, jiange91 approved these changes

2024-12-12 21:20 UTC, merged